package hevs.androiduino.dsl.generator

import java.io.PrintWriter

import grizzled.slf4j.Logging
import hevs.androiduino.dsl.components.ComponentManager
import hevs.androiduino.dsl.utils.OSUtils._
import hevs.androiduino.dsl.utils.{OSUtils, Version}

import scala.sys.process._

object CodeGenerator extends Logging {

  def generateCode(progName: String): String = {

    checkWarnings()

    val result =
      preamble(progName) +
        ComponentManager.generateConstantsCode +
        ComponentManager.generateFunctionsCode +
        preInit() +
        ComponentManager.generateInitCode +
        postInit() +
        beginMain() +
        ComponentManager.generateBeginMainCode +
        beginLoopMain() +
        ComponentManager.generateLoopingCode +
        endLoopMain() +
        endMain(progName)

    result
  }

  def checkWarnings(): Boolean = {
    val c = ComponentManager.findUnconnectedComponents
    if (c.size > 0) {
      println("WARN: Unconnected component(s) found:")
      println("\t- " + c.mkString("\n\t- "))
      return true
    }
    false // No warnings
  }

  def preamble(progName: String) = {
    val ver = Version.getVersion
    "/*" + "\n" +
      " " + "*".*(60) + "\n" +
      s" Generated by AndroidUINO generator / mui 2013\n" +
      s" Version $ver\n" +
      s" Program '$progName.c'\n" +
      " " + "*".*(60) + "\n" +
      " */\n\n"
  }

  def preInit() = "void init() {\n"

  def postInit() = "}\n\n"

  def beginMain() = "int main() {\n"

  def beginLoopMain() = "while(1){\n"

  def endLoopMain() = "}\n"

  def endMain(fileName: String) = s"}\n// END of '$fileName.c'"

  def outputToFile(fileName: String, code: String) = {
    val writer = new PrintWriter(fileName)
    writer.print(code)
    writer.close()

    println()
    info("Running Astyle...")
    OSUtils.getOsType match {
      case _: Windows => {
        // Call the AStyle conversion program on windows
        s"./lib/AStyle.exe --style=kr -Y $fileName".!!
      }
      case _: Linux => {
        s"./lib/astyle --style=kr -Y $fileName".!!
      }
      case _ => error("OS not supported. Cannot run `astyle`.")
    }
  }
}