/*
 * * * * * * * * * * * * * * * * * * * *
 Generated by AndroidUINO generator / mui 2013
 Version 0.1.1
 * * * * * * * * * * * * * * * * * * * *
 */

const bool _autoCst1 = false;
const bool _autoCst1 = false;
void init()
{
    // This is the init code for the init of an led
    int reg_led4 = init_value; // TODO replace this with real code
}


int main()
{

    // Propagating constants
    led4 = _autoCst1;

    // Propagating constants
    led4 = _autoCst1;


    while(1) {
    }
}
