/*
 * * * * * * * * * * * * * * * * * * * *
 Generated by AndroidUINO generator / mui 2013
 Version 0.1.1
 * * * * * * * * * * * * * * * * * * * *
 */

void pollButton3(){
	if(valueHasChanged){
		led4 = buttonValue3;
		led2 = buttonValue3;
	}
} // End of function def for HW_Button

void init(){
	// This is the init code for the init of an led
	int reg_led2 = init_value; // TODO replace this with real code
	// This is the init code for the init of an led
	int reg_led4 = init_value; // TODO replace this with real code
	// This is the init code for the init of a button
	button3.setAsOutput; // TODO replace this with real code
}


int main(){
	

	while(1){
		pollButton3();
}}
